### ISSUE TITLE
feat: add aliases into wait keyword for cypress tests

### ISSUE THREAD

**Issue by lucas-louis** [PoCInnovation/InterPlanetaryCloud#19]
# [FEATURES] Add wait aliases for cypress tests

## Description

In order to avoid crashed tests with cypress, because of the too long time response for the loading/ downloading/ uploading, the use of aliases into the tests will be good.

## Is your feature request related to a problem? Please describe.

Sometimes, the loading/ uploading/ downloading is too long for the tests, so they crashed.

## Describe the solution you'd like

The use of [aliases](https://docs.cypress.io/api/commands/wait#Alias) with the wait keyword, will fix this problem.
The wait keyword could wait with a specific time (like all the tests right now) *AND* with a condition too, like "you wait until this event is triggered".
So instead of putting a wait of 2 seconds, for example, we could put a wait until a specific toast is displayed (the toast is the one telling that the download/ load/ upload is done)

**Comment by RezaRahemtola** [comment]
Using aliases is not needed for `cy.visit()` as it already [waits for the page to load](https://docs.cypress.io/guides/core-concepts/introduction-to-cypress#Default-Values).

A lot of useless waits where removed so the e2e tests are now 17% faster.

I‘m closing this issue and moving the remaining part in a bullet point of #27
