### ISSUE TITLE
fix: can't upload an empty file

### ISSUE THREAD

**Issue by lucas-louis** [PoCInnovation/InterPlanetaryCloud#25]
# [BUG] [Can't upload an empty file]

## Description

When you try to upload an empty file, you can click on the `Upload a file` button, but nothing is happening.

## Your environment

* Ubuntu 20.04 LTS
* master

## Steps to reproduce

* Create an empty file, for example `touch test.txt`
* In the `Upload a file` modal, select the created file
* Click on the `Upload a file` button

## Expected behaviour

The button should upload the selected file, even if it's empty, to simulate a working behaviour, you can upload a file which is not empty.

## Actual behaviour

The button does nothing.

## Proposed solution

Maybe check the read function for the given file.

**Comment by RezaRahemtola** [comment]
Working behavior simulated by displaying an error toast and closing the modal if the file is empty.
A cypress test was added to make sure the modal closes and no content is uploaded to Aleph
