### ISSUE TITLE
feat: add files permissions & automatic update shared files

### ISSUE THREAD

**Issue by lucas-louis** [PoCInnovation/InterPlanetaryCloud#29]
# [FEATURES] [Add files permissions & automatic update shared files]

## Description

- Add file permissions (read, write)
- Add the possibility to edit a file for every contacts who have the permission to see this file

## Describe the solution you'd like

When a contact updates a shared file, all the contacts linked to this file can access to the new version of the file uploaded by the editor. Only the contacts with the 'writing' permission can update the files.

## Additional context

- :warning: This issue is linked to the #28

**Comment by RezaRahemtola** [comment]
> When a contact updates a shared file, all the contacts linked to this file can access to the new version of the file uploaded by the editor. 
This part is implemented in #61.
