### ISSUE TITLE
[Feature]: Create an editable file for config settings

### ISSUE THREAD

**Issue by RezaRahemtola** [PoCInnovation/InterPlanetaryCloud#89]
### Description

Create a config file editable in IPC :rocket: 

### Expected behaviour

- Think about it: 
    - [x] How to display it?
    - [x] Which format will be used,?
    - [x] How will you store it on Aleph? :wink:
- Create the corresponding UI editor :rocket: 

### Environment

/

**Comment by ZerLock** [comment]
> ### Description
> Create a config file editable in IPC rocket
> 
> ### Expected behaviour
> * Think about it:
>   
>   * [ ]  How to display it?
>   * [ ]  Which format will be used,?
>   * [ ]  How will you store it on Aleph? wink
> * Create the corresponding UI editor rocket
> 
> ### Environment
> /
> 
> ### Proposed solution
> _No response_

**How to display it:** A new tab just after 'My profile' named 'Configuration' with a lot of **_inputs_** to edit the config
**Which format will be used:** I think JSON. Basic, universal, clean :ok_hand: 
**How will you store it on Aleph:** In aggregates we will store it like any files. However, not in the files array but in a new property named 'configuration'
